// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Home Page documents */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home Page → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = PackageCarouselSlice;
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
export type AllDocumentTypes = HomepageDocument;
/**
 * Primary content in Carousel → Primary
 *
 */
interface PackageCarouselSliceDefaultPrimary {
  /**
   * Anchor Id field in *Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: package_carousel.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  anchor_id: prismic.KeyTextField;
}
/**
 * Item in Carousel → Items
 *
 */
export interface PackageCarouselSliceDefaultItem {
  /**
   * Package Title field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: package_carousel.items[].package_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  package_title: prismic.KeyTextField;
  /**
   * Package Price field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: package_carousel.items[].package_price
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  package_price: prismic.KeyTextField;
  /**
   * Package Info field in *Carousel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: package_carousel.items[].package_info
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  package_info: prismic.RichTextField;
  /**
   * Package BG Color field in *Carousel → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: package_carousel.items[].package_bg_color
   * - **Documentation**: https://prismic.io/docs/core-concepts/color
   *
   */
  package_bg_color: prismic.ColorField;
}
/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PackageCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PackageCarouselSliceDefaultPrimary>,
  Simplify<PackageCarouselSliceDefaultItem>
>;
/**
 * Slice variation for *Carousel*
 *
 */
type PackageCarouselSliceVariation = PackageCarouselSliceDefault;
/**
 * Carousel Shared Slice
 *
 * - **API ID**: `package_carousel`
 * - **Description**: `PackageCarousel`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PackageCarouselSlice = prismic.SharedSlice<
  "package_carousel",
  PackageCarouselSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocument,
      AllDocumentTypes,
      PackageCarouselSliceDefaultPrimary,
      PackageCarouselSliceDefaultItem,
      PackageCarouselSliceDefault,
      PackageCarouselSliceVariation,
      PackageCarouselSlice,
    };
  }
}
