// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  package_carousel: dynamic(() => import("./Carousel")),
  reviews_carousel: dynamic(() => import("./ReviewsCarousel")),
};
